config/routes.rb
Rails.application.routes.draw do
  resources :collaborators
  devise_for :users
  resources :wikis

  get 'about' => 'welcome#about'
  root 'welcome#index'

  resources :charges, only: [:new, :create] do
    collection do
      get :downgrade
    end
  end

end

app/models/amount.rb
# class Amount
#   def default
#     return 15_00
#   end
# end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators
  has_many :shared_wikis, through: :collaborators, source: :wiki
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  after_initialize { self.role ||= :standard }

  enum role: [:standard, :premium, :admin]


end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  after_action :role_to_premium, only: :create

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    @amount = 15_00

    customer = Stripe::Customer.create(
        email: current_user.email,
        card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in your app
        amount: @amount,
        description: "BigMoney Membership - #{current_user.email}",
        currency: 'usd'
    )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to  wikis_path
      # return

      # Stripe will send back CardErrors, with friendly messages
      # when something goes wrong.
      # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: "BigMoney Membership - #{current_user.email}",
        amount: @amount
    }
  end

  def downgrade
    current_user.wikis.where(private: true).each { |wiki| wiki.update_attribute(:private, false) }
    set_to_standard
    redirect_to wikis_path
  end

end

private

def role_to_premium
  current_user.premium!
end

def set_to_standard
  current_user.standard!
  # redirect_to wikis_path
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_collaborator, only: [:show, :edit, :update, :destroy]

  # GET /collaborators
  def index
    @collaborators = Collaborator.all
  end

  # GET /collaborators/1
  def show
  end

  # GET /collaborators/new
  def new
    @collaborator = Collaborator.new
  end

  # GET /collaborators/1/edit
  def edit
  end

  # POST /collaborators
  def create
    @collaborator = Collaborator.new(collaborator_params)

    if @collaborator.save
      redirect_to @collaborator, notice: 'Collaborator was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /collaborators/1
  def update
    if @collaborator.update(collaborator_params)
      redirect_to @collaborator, notice: 'Collaborator was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /collaborators/1
  def destroy
    @collaborator.destroy
    redirect_to collaborators_url, notice: 'Collaborator was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaborator
      @collaborator = Collaborator.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def collaborator_params
      params.require(:collaborator).permit(:user_id, :wiki_id)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis

  def index
    @wikis = policy_scope(Wiki)
  end

  # GET /wikis/1
  def show
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  def create
    @wiki = Wiki.new(wiki_params)

    if @wiki.save
      redirect_to @wiki, notice: 'Wiki was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /wikis/1
  def update
    if @wiki.update(wiki_params)
      redirect_to @wiki, notice: 'Wiki was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /wikis/1
  def destroy
    @wiki.destroy
    redirect_to wikis_url, notice: 'Wiki was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <h4>Click the button!</h4>
    <% if !current_user.premium? %>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
    <% elsif current_user.premium? %>
        <p>Do you want to Cancel?<p>
        <%= link_to "Cancel Subscription" , {:controller => :charges, :action => :downgrade}, method: :get%>
    <% end %>
<% end %>

app/views/collaborators/_form.html.erb
<%= form_for(@collaborator) do |f| %>
  <% if @collaborator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collaborator.errors.count, "error") %> prohibited this collaborator from being saved:</h2>

      <ul>
      <% @collaborator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :wiki_id %><br>
    <%= f.text_field :wiki_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collaborators/edit.html.erb
<h1>Editing Collaborator</h1>

<%= render 'form' %>

<%= link_to 'Show', @collaborator %> |
<%= link_to 'Back', collaborators_path %>

app/views/collaborators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collaborators</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Wiki</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collaborators.each do |collaborator| %>
      <tr>
        <td><%= collaborator.user.email %></td>
        <td><%= collaborator.wiki.title %></td>
        <td><%= link_to 'Show', collaborator %></td>
        <td><%= link_to 'Edit', edit_collaborator_path(collaborator) %></td>
        <td><%= link_to 'Destroy', collaborator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collaborator', new_collaborator_path %>

app/views/collaborators/new.html.erb
<h1>New Collaborator</h1>

<%= render 'form' %>

<%= link_to 'Back', collaborators_path %>

app/views/collaborators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @collaborator.user.email %>
</p>

<p>
  <strong>Wiki:</strong>
  <%= @collaborator.wiki.title %>
</p>

<%= link_to 'Edit', edit_collaborator_path(@collaborator) %> |
<%= link_to 'Back', collaborators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
    Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% if current_user.premium?%>
        - <%= link_to "Downgrade to Standard?", new_charge_path, method: :get  %>
    <%else  %>
        - <%= link_to "Upgrade to Premium?", new_charge_path, method: :get  %>

    <% end %>
<% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to the Blocipedia welcome page!</h1>
<% if current_user.premium? || current_user.admin? %>
    <%= link_to "View all Wikis" , wikis_path , method: :get%><br>
    <%= link_to "View all Collaborators" , collaborators_path , method: :get%><br>
    <%= link_to "Downgrade to Standard?", new_charge_path, method: :get  %>
<%else  %>
<%end%>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
    <% if @wiki.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

          <ul>
            <% @wiki.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>
    <% if current_user.premium? || current_user.admin?%>
        <div class="field">
          <%= f.label :private %><br>
          <%= f.check_box :private %><br>
          <%= link_to "Add a collaborator?" , new_collaborator_path , method: :get%>
        </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wikis</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Private</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= wiki.title %></td>
        <td><%= markdown(wiki.body) %></td>
        <td><%= wiki.private %></td>
        <td><%= User.find(wiki.user_id).email %></td>
        <td><%= link_to 'Show', wiki %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@wiki.body) %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>

<p>
  <strong>User:</strong>
  <%= User.find(@wiki.user_id).email %>
</p>

<%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<%= link_to 'Back', wikis_path %>